name: collagelabs

services:
  server:
    type: node
    run:
      - ln -s /user/.cache /home/node/.cache
      - bundle config path vendor/bundle
      - bundle config cache_path /home/node/.cache/bundler
      - bundle install
      - bundle package
      - yarn install
    moreHttpPorts:
      - '5000'
      - '5001'
      - '3000'
      - '9000'
    overrides:
      image: collagelabs/collagelabs.github.io:latest
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - '5000:5000'
        - '5001:5001'
        - '3000:5000'
        - '9000:9000'

tooling:
  yarn:
    service: server
  bash:
    service: server