sudo: required
services: docker
dist: xenial
languages: minimal
branches:
    only:
        - develop
        - /^greenkeeper/.*$/
before_script:
    - curl -sLO https://github.com/lando/lando/releases/download/v3.0.0-rc.17/lando-v3.0.0-rc.17.deb && sudo dpkg -i lando-v3.0.0-rc.17.deb
    - rm lando-v3.0.0-rc.17.deb
script:
    - lando start
    - lando yarn run build:pwa
