name: 'Collage Labs'
app_name: 'Collage Labs'
title: A blog about Free Software and Society
description: A blog about Free Software and Society.
author:
  name: 'Luis Alejandro Martínez Faneyth'
  first_name: 'Luis Alejandro'
  last_name: 'Martínez Faneyth'
  email: 'luis@luisalejandro.org'
  github: 'LuisAlejandro'
  twitter: 'LuisAlejandro'
  facebook: 'martinez.faneyth'
  paypal: 'martinezfaneyth'
blog:
  twitter: 'HuntingBearsWeb'
  facebook: 'HuntingBearsWeb'
  instagram: 'HuntingBearsWeb'
  googleplus: 'HuntingBearsVE'
  feed: 'HuntingBearsWeb'

google_analytics: id
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

facebook:
  - app_id: 409501159152943
  - admins: 870375116
  - profile_id: 870375116
  - publisher: 156686441067299

ampdir: amp
port: 3000

lang: en
lang_locale: en_US

collections_dir: collections
collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/

pagination:
  per_page: 20
  permalink: '/page/:num/'

autopages:
  categories: 
    layouts: 
      - 'category.html'
    title: 'Posts in category :cat'
    permalink: '/blog/category/:cat'
  tags:
    layouts: 
      - 'tag.html'
    title: 'Posts tagged with :tag'
    permalink: '/blog/tag/:tag'

markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - amp-jekyll
  - octopress-minify-html

exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - Makefile
  - node_modules
  - vendor
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.svg
  - HISTORY.md
  - MAINTAINER.md
