name: 'Collage Labs'
app_name: 'Collage Labs'
title: Web, Mobile, ERP & IT Solutions
description: Collage Labs is building software for multiple digital agencies across the globe. Our team provides personal, professional and friendly service which carefully considers your business goals and requirements.
author:
  name: 'Collage Labs'
  email: 'contact@collagelabs.org'
  github: 'CollageLabs'
  twitter: 'CollageLabs'
  facebook: 'CollageLabs'
  paypal: 'martinezfaneyth'
blog:
  twitter: 'CollageLabs'
  facebook: 'CollageLabs'
  instagram: 'collagelabsco'

google_analytics: UA-157866327-1
webmaster_verifications:
  google: ""
  bing: ""
  alexa: ""
  yandex: ""
  baidu: ""

facebook:
  - app_id: ""
  - admins: ""
  - profile_id: ""
  - publisher: ""

ampdir: amp
port: 3000

lang: en
lang_locale: en_US

collections_dir: collections
collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/

pagination:
  per_page: 20
  permalink: '/page/:num/'

autopages:
  categories:
    layouts:
      - 'category.html'
    title: 'Posts in category :cat'
    permalink: '/blog/category/:cat'
  tags:
    layouts:
      - 'tag.html'
    title: 'Posts tagged with :tag'
    permalink: '/blog/tag/:tag'

markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - amp-jekyll
  - octopress-minify-html

exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - Makefile
  - node_modules
  - vendor
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.svg
  - HISTORY.md
  - MAINTAINER.md
  - functions
  - lambda
