name: Collage Labs
app_name: Collage Labs
title: Web, Mobile, ERP & IT Solutions
description: Collage Labs is building software for multiple digital agencies across the globe. Our team provides personal, professional and friendly service which carefully considers your business goals and requirements.
author:
  name: Collage Labs
  email: contact@collagelabs.org
  github: CollageLabs
  twitter: CollageLabs
  facebook: CollageLabs
  paypal: martinezfaneyth
blog:
  twitter: CollageLabs
  facebook: CollageLabs
  instagram: collagelabsco

google_analytics: G-MPV2HWKZTF
recaptcha_key: 6LfE-6gfAAAAAP7tAI8tndckzX5Y7NwvYODyDyFr
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:

facebook:
  - app_id:
  - admins:
  - profile_id:
  - publisher:

ampdir: amp
port: 3000

lang: en
lang_locale: en_US

collections_dir: collections
collections:
  posts:
    title: Posts
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/

pagination:
  per_page: 20
  permalink: /page/:num/

incremental: true

autopages:
  categories:
    layouts:
      - category.html
    title: Posts in category :cat
    permalink: /blog/category/:cat
  tags:
    layouts:
      - tag.html
    title: Posts tagged with :tag
    permalink: /blog/tag/:tag

markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - amp-jekyll
  - octopress-minify-html

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - Dockerfile
  - Makefile
  - node_modules
  - vendor
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - dist
  - icon.svg
  - HISTORY.md
  - MAINTAINER.md
  - functions
  - lambda
