version: "3"
services:
  app:
    image: collagelabs/collagelabs.org:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/collagelabs/app
    env_file:
      - .env
    ports:
      - '5000:5000'
      - '5001:5001'
      - '3000:5000'
      - '9000:9000'