version: "3"
services:
  collagelabs:
    image: collagelabs/collagelabs.github.io:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/collagelabs/app
    ports:
      - '5000:5000'
      - '5001:5001'
      - '3000:5000'
      - '9000:9000'