name: Code Analysis

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '42 14 * * 5'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript
      - name: Installing dependencies
        run: |
          curl -sLO https://files.devwithlando.io/lando-stable.deb
          sudo dpkg -i --ignore-depends=docker-ce *.deb
      - name: Caching ruby gems
        uses: actions/cache@v2
        with:
          path: ~/.cache/bundler
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Caching node packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Building project
        run: |
          lando start
          lando yarn run build:pwa
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
