name: Push

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Initialize Code Analysis
        uses: github/codeql-action/init@v1
        with:
          languages: javascript
      - name: Installing dependencies
        run: |
          curl -sLO https://files.devwithlando.io/lando-stable.deb
          sudo dpkg -i --ignore-depends=docker-ce *.deb
      - name: Building project
        run: |
          lando start
          lando yarn run build:pwa
      - name: Perform Code Analysis
        uses: github/codeql-action/analyze@v1