name: Push

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Restoring node_modules cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Restoring vendor/bundle cache
        uses: actions/cache@v2
        with:
          path: 'vendor/bundle'
          key: ${{ runner.os }}-vendor-bundle-${{ hashFiles('Gemfile.lock') }}
      - name: Login to Github Docker Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Pulling docker cache
        run: docker pull ghcr.io/$GITHUB_REPOSITORY/collagelabs-build-cache || true
      - name: Building image with cache
        run: docker build . -t collagelabs/collagelabs.github.io:latest --cache-from=ghcr.io/$GITHUB_REPOSITORY/collagelabs-build-cache
      - name: Building project
        run: |
          sudo chown -R 1000:1000 .
          make start
          make dependencies
          make build_production
          sudo chown -R runner:docker .
      - name: Pushing docker image
        run: docker tag collagelabs/collagelabs.github.io:latest ghcr.io/$GITHUB_REPOSITORY/collagelabs-build-cache && docker push ghcr.io/$GITHUB_REPOSITORY/collagelabs-build-cache || true
